<?php

 /*
 * Adding a require once is kind of belt and suspenders for the generalMetricSaver
 *
 * So far, these returns are going to be non-metric results
 * will disable by default and can enable later if it makes sensee
 */
 // require_once __DIR__ . "/../../../../templates/generalMetricSaver.php";

 /*
 * Checks if a remote host and port are accessible.
 *
 * @param string $host The remote host (IP address or domain name).
 * @param int $port The port number to check.
 * @param int $timeout The connection timeout in seconds.
 * @return bool True if the port is open, false otherwise.
 */
function isPortOpen(string $host, int $port, int $timeout = null): bool
{
    // Set default for timeout if needed to 3 seconds
    $timeout = (int)($timeout ?? 3);
    // Suppress warnings generated by fsockopen for connection errors
    $socket = @fsockopen($host, $port, $errno, $errstr, $timeout);

    if ($socket) {
        fclose($socket); // Close the connection if successful
        return true;
    } else {
        // You can log $errno and $errstr for debugging if needed
        // error_log("Failed to connect to $host:$port - Error $errno: $errstr");
        return false;
    }
}

?>
